RWA-1522 - Remove task configuration code
hmcts/camunda-bpm pull request #379
Opened 2022-09-02 12:59 UTC by sullivangareth

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RWA-1522

### Change description ###

Remove task configuration code

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-09-02 14:38 UTC, burale approved these changes
LGTM

2022-09-05 16:32 UTC, raghera commented on src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/EventHandlerConfiguration.java
> -            delegateTask.setVariableLocal(CFT_TASK_STATE_LOCAL_VARIABLE_NAME, "unconfigured");
we will want to keep this line.  Discussed with @burale so don't think we can remove this handler completely.

2022-09-05 16:34 UTC, raghera requested changes
The ticket this depends on has a problem with it.  On review we can't remove this method completely since we still need one line which is essential for Task creation.

2022-10-06 11:07 UTC, rafalkalita commented on src/main/java/uk/gov/hmcts/reform/camunda/bpm/config/EventHandlerConfiguration.java
> -            delegateTask.setVariableLocal(CFT_TASK_STATE_LOCAL_VARIABLE_NAME, "unconfigured");
Updated the PR. Left the line untouched and updated tests.

2022-10-10 11:07 UTC, raghera approved these changes

2022-10-12 12:18 UTC, merged