Extending supression
hmcts/camunda-bpm pull request #681
Opened 2023-11-14 10:04 UTC by jordankainos

### Jira link (if applicable)

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2023-11-14 10:09 UTC, ieuanb74 approved these changes

2023-11-14 10:15 UTC, adusumillipraveen approved these changes

2023-11-16 09:15 UTC, timja requested changes

2023-11-16 09:15 UTC, timja commented on config/owasp/suppressions.xml
> +  <suppress until="2023-12-04">
```suggestion
  <suppress>
```

2023-11-16 09:15 UTC, timja commented on config/owasp/suppressions.xml
>     ** DISPUTED ** An issue was discovered jackson-databind thru 2.15.2 allows attackers to cause a denial of service or other unspecified impacts via crafted object that uses cyclic dependencies. NOT
```suggestion
   This is a junk CVE, see https://github.com/FasterXML/jackson-databind/issues/3972#issuecomment-1813589383
```

2024-02-07 13:40 UTC, timja approved these changes

2024-02-07 13:44 UTC, merged